//gen file for Evo
#ifdef __INTELLISENSE__
const struct SpeciesInfo gSpeciesInfoEvo[] =
{

	[SPECIES_ECOSAUR] =
	{
		.speciesName = _("Ecosaur"),
		.baseHP = 84,
		.baseAttack = 90,
		.baseDefense = 85,
		.baseSpeed = 80,
		.baseSpAttack = 118,
		.baseSpDefense = 118,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 204,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = GROWTH_MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = TRUE,
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Overgrown"),
		.height = 20,
		.weight = 2700,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.iconPalIndex = 2,
		.evolutions = EVOLUTION({EVO_LEVEL, 52, SPECIES_TERARISAUR}),
	},

	[SPECIES_TERARISAUR] =
	{
		.speciesName = _("Terarisaur"),
		.baseHP = 90,
		.baseAttack = 106,
		.baseDefense = 91,
		.baseSpeed = 80,
		.baseSpAttack = 129,
		.baseSpDefense = 129,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 215,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = GROWTH_MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = TRUE,
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Jungle"),
		.height = 20,
		.weight = 3500,
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.iconPalIndex = 2,
		.evolutions = EVOLUTION({EVO_LEVEL, 65, SPECIES_SYMBISAUR}),
	},

#ifdef __INTELLISENSE__
};
#endif
//end of program