//learnset for PkmnEvolved
#define LEVEL_UP_MOVE(lvl, moveLearned) {.move = moveLearned, .level = lvl}
#define LEVEL_UP_END {.move = LEVEL_UP_MOVE_END, .level = 0}

static const struct LevelUpMove sNoneLevelUpLearnset[] = {
    LEVEL_UP_MOVE(1, MOVE_POUND),
    LEVEL_UP_END
};
#endif

static const struct LevelUpMove sEcosaurLevelUpLearnset[] = {
	LEVEL_UP_MOVE( 1 , MOVE_GROWL),
	LEVEL_UP_MOVE( 1 , MOVE_LEECH_SEED),
	LEVEL_UP_MOVE( 1 , MOVE_VINE_WHIP),
	LEVEL_UP_MOVE( 4 , MOVE_GROWL),
	LEVEL_UP_MOVE( 7 , MOVE_LEECH_SEED),
	LEVEL_UP_MOVE( 10 , MOVE_VINE_WHIP),
	LEVEL_UP_MOVE( 15 , MOVE_POISON_POWDER),
	LEVEL_UP_MOVE( 15 , MOVE_SLEEP_POWDER),
	LEVEL_UP_MOVE( 22 , MOVE_RAZOR_LEAF),
	LEVEL_UP_MOVE( 29 , MOVE_SWEET_SCENT),
	LEVEL_UP_MOVE( 34 , MOVE_SLUDGE_BOMB),
	LEVEL_UP_MOVE( 41 , MOVE_GROWTH),
	LEVEL_UP_MOVE( 46 , MOVE_GIGA_DRAIN),
	LEVEL_UP_MOVE( 53 , MOVE_SYNTHESIS),
	LEVEL_UP_MOVE( 65 , MOVE_SOLARBEAM),
	LEVEL_UP_MOVE( 70 , MOVE_FRENZY_PLANT),
	LEVEL_UP_END
};

static const struct LevelUpMove sTerarisaurLevelUpLearnset[] = {
	LEVEL_UP_MOVE( 1 , MOVE_GROWL),
	LEVEL_UP_MOVE( 1 , MOVE_LEECH_SEED),
	LEVEL_UP_MOVE( 1 , MOVE_VINE_WHIP),
	LEVEL_UP_MOVE( 4 , MOVE_GROWL),
	LEVEL_UP_MOVE( 7 , MOVE_LEECH_SEED),
	LEVEL_UP_MOVE( 10 , MOVE_VINE_WHIP),
	LEVEL_UP_MOVE( 15 , MOVE_POISON_POWDER),
	LEVEL_UP_MOVE( 15 , MOVE_SLEEP_POWDER),
	LEVEL_UP_MOVE( 22 , MOVE_RAZOR_LEAF),
	LEVEL_UP_MOVE( 29 , MOVE_SWEET_SCENT),
	LEVEL_UP_MOVE( 34 , MOVE_SLUDGE_BOMB),
	LEVEL_UP_MOVE( 41 , MOVE_GROWTH),
	LEVEL_UP_MOVE( 46 , MOVE_GIGA_DRAIN),
	LEVEL_UP_MOVE( 53 , MOVE_SYNTHESIS),
	LEVEL_UP_MOVE( 65 , MOVE_SOLARBEAM),
	LEVEL_UP_MOVE( 70 , MOVE_FRENZY_PLANT),
	LEVEL_UP_END
};
