#define SPECIES_ECOSAUR                                  1573
#define SPECIES_TERARISAUR                               1574
#define SPECIES_SYMBISAUR                                1575
#define SPECIES_CHARIGUANA                               1576
#define SPECIES_CHARIANA                                 1577
#define SPECIES_CHARIATHAN                               1578
#define SPECIES_FERRAPIN                                 1579
#define SPECIES_FORTOISE                                 1580
#define SPECIES_TURTILLERY                               1581
#define SPECIES_BUTTEFLARE                               1582
#define SPECIES_PYREFREE                                 1583
#define SPECIES_IMPSECT                                  1584
#define SPECIES_BEEBRUTE                                 1585
#define SPECIES_DRONARCH                                 1586
#define SPECIES_SEPISTRIKE                               1587
#define SPECIES_PIDGAERO                                 1588
#define SPECIES_PIDGEOZONE                               1589
#define SPECIES_PIDGEPHYR                                1590
#define SPECIES_RATTCHET                                 1591
#define SPECIES_RATTARULE                                1592
#define SPECIES_SNEEROW                                  1593
#define SPECIES_ORNITHOW                                 1594
#define SPECIES_NOHTYP                                   1595
#define SPECIES_ADNOKANA                                 1596
#define SPECIES_GOROCHU                                  1597
#define SPECIES_STROMACHU                                1598
#define SPECIES_SANDSLAM                                 1599
#define SPECIES_FERODILLO                                1600
#define SPECIES_NIDOREGAL                                1601
#define SPECIES_NIDOARCHY                                1602
#define SPECIES_NIDORULY                                 1603
#define SPECIES_NIDOMINATE                               1604
#define SPECIES_CLEFAEFAE                                1605
#define SPECIES_CLEFANAUT                                1606
#define SPECIES_SPIRITALES                               1607
#define SPECIES_YOKAYUBI                                 1608
#define SPECIES_GIGGLYHUFF                               1609
#define SPECIES_BOGGLYFUFF                               1610
#define SPECIES_POLABAT                                  1611
#define SPECIES_VISIBAT                                  1612
#define SPECIES_HORRIBAT                                 1613
#define SPECIES_RAFFLURK                                 1614
#define SPECIES_CONCORPSIA                               1615
#define SPECIES_SECTASITE                                1616
#define SPECIES_FUNGALITH                                1617
#define SPECIES_VENOMENA                                 1618
#define SPECIES_VENOMENON                                1619
#define SPECIES_DUGROUPLE                                1620
#define SPECIES_UNEARTHLET                               1621
#define SPECIES_DIGLENOID                                1622
#define SPECIES_FELANKH                                  1623
#define SPECIES_PATRAPHINX                               1624
#define SPECIES_GILDUCK                                  1625
#define SPECIES_PLATINUPUS                               1626
#define SPECIES_GORILLASH                                1627
#define SPECIES_BONUMBELL                                1628
#define SPECIES_SINGESHA                                 1629
#define SPECIES_GUARDIANCE                               1630
#define SPECIES_POLITOES                                 1631
#define SPECIES_POLIWISE                                 1632
#define SPECIES_POLIATH                                  1633
#define SPECIES_SIMSALABIM                               1634
#define SPECIES_VOHOODU                                  1635
#define SPECIES_TZARKARTZ                                1636
#define SPECIES_MACHULK                                  1637
#define SPECIES_ABOMACHULK                               1638
#define SPECIES_MACHITAN                                 1639
#define SPECIES_MUCKTRIBEL                               1640
#define SPECIES_CARNABELL                                1641
#define SPECIES_DEVLORA                                  1642
#define SPECIES_TENTACATE                                1643
#define SPECIES_TENTABOMA                                1644
#define SPECIES_SLAGOLEM                                 1645
#define SPECIES_MOLTREM                                  1646
#define SPECIES_VOLCANICOL                               1647
#define SPECIES_COMBUSTANG                               1648
#define SPECIES_KNIGHTMARE                               1649
#define SPECIES_SLOWMATE                                 1650
#define SPECIES_SLOWCHUM                                 1651
#define SPECIES_MAGNEMELD                                1652
#define SPECIES_MAGNEMASTR                               1653
#define SPECIES_FORFOWLD                                 1654
#define SPECIES_FOWLNTOM                                 1655
#define SPECIES_QUADODO                                  1656
#define SPECIES_DODOZEN                                  1657
#define SPECIES_PRECIPED                                 1658
#define SPECIES_MANATII                                  1659
#define SPECIES_GUNK                                     1660
#define SPECIES_SKUM                                     1661
#define SPECIES_ANENEMY                                  1662
#define SPECIES_GLAISHELL                                1663
#define SPECIES_GENGONE                                  1664
#define SPECIES_POLTERGAST                               1665
#define SPECIES_GRIMM                                    1666
#define SPECIES_PLATNIX                                  1667
#define SPECIES_OBSIDIANIX                               1668
#define SPECIES_STALAGMIX                                1669
#define SPECIES_LULLOO                                   1670
#define SPECIES_SOMNISOOTH                               1671
#define SPECIES_KRAKLAW                                  1672
#define SPECIES_TEKLAWNO                                 1673
#define SPECIES_ELECTRODES                               1674
#define SPECIES_ELECTRODEX                               1675
#define SPECIES_ELECTRODEM                               1676
#define SPECIES_EXEGGITY                                 1677
#define SPECIES_EXEGGTRIC                                1678
#define SPECIES_OSSELOBBER                               1679
#define SPECIES_WRAIWRATH                                1680
#define SPECIES_CLEEVOYANT                               1681
#define SPECIES_SPIRITULEE                               1682
#define SPECIES_ENCHANCED                                1683
#define SPECIES_RADIACHAN                                1684
#define SPECIES_LICKILOLLY                               1685
#define SPECIES_LICKILATO                                1686
#define SPECIES_HEEVING                                  1687
#define SPECIES_CHOHKING                                 1688
#define SPECIES_RHYMARKABL                               1689
#define SPECIES_RHYLIC                                   1690
#define SPECIES_RHYBORN                                  1691
#define SPECIES_GOGETTEY                                 1692
#define SPECIES_LUKKEY                                   1693
#define SPECIES_FORTUNITEY                               1694
#define SPECIES_TANGATHER                                1695
#define SPECIES_TANGOLIATH                               1696
#define SPECIES_TANGRAPPLE                               1697
#define SPECIES_KANGAKID                                 1698
#define SPECIES_KANGALLOUS                               1699
#define SPECIES_KANGARUTAL                               1700
#define SPECIES_LORDRA                                   1701
#define SPECIES_PINNADRA                                 1702
#define SPECIES_SEAREX                                   1703
#define SPECIES_CAPRISEA                                 1704
#define SPECIES_STARUS                                   1705
#define SPECIES_STARWE                                   1706
#define SPECIES_MR_JEST                                  1707
#define SPECIES_MR_FOOL                                  1708
#define SPECIES_RAZER                                    1709
#define SPECIES_CLAYMOR                                  1710
#define SPECIES_JYNKIES                                  1711
#define SPECIES_JEEPERS                                  1712
#define SPECIES_ELECTIVINE                               1713
#define SPECIES_ELECTIWIZZ                               1714
#define SPECIES_MAGMORE                                  1715
#define SPECIES_MAGMOLTEN                                1716
#define SPECIES_PINSIRIOR                                1717
#define SPECIES_ABYSSIR                                  1718
#define SPECIES_TAUROX                                   1719
#define SPECIES_OXENFREE                                 1720
#define SPECIES_HYDRADOS                                 1721
#define SPECIES_DRACOSMIC                                1722
#define SPECIES_QUAZAR                                   1723
#define SPECIES_LOCHLASS                                 1724
#define SPECIES_NESSEA                                   1725
#define SPECIES_MORPHO                                   1726
#define SPECIES_METAMORPHO                               1727
#define SPECIES_RIVEON                                   1728
#define SPECIES_BRINEON                                  1729
#define SPECIES_PLASMEON                                 1730
#define SPECIES_GALVEON                                  1731
#define SPECIES_SMOLDEON                                 1732
#define SPECIES_INFERNEON                                1733
#define SPECIES_PORYGONX                                 1734
#define SPECIES_PORYGONQ                                 1735
#define SPECIES_PORYGON2A4                               1736
#define SPECIES_OMAPAL                                   1737
#define SPECIES_OMAGUS                                   1738
#define SPECIES_KABUTAK                                  1739
#define SPECIES_KABUSTION                                1740
#define SPECIES_MANDILUFT                                1741
#define SPECIES_AMBALITHIC                               1742
#define SPECIES_ACTLAX                                   1743
#define SPECIES_GRIZZLAX                                 1744
#define SPECIES_SNOWONE                                  1745
#define SPECIES_FROSTUNUS                                1746
#define SPECIES_SHOCKATOO                                1747
#define SPECIES_VOLTDUO                                  1748
#define SPECIES_IGNITHREE                                1749
#define SPECIES_INFERNTRI                                1750
#define SPECIES_DRAGONIER                                1751
#define SPECIES_DRAGONACE                                1752
#define SPECIES_DRAGONTALE                               1753
#define SPECIES_MEWTHREE                                 1754
#define SPECIES_MEWFOUR                                  1755
#define SPECIES_NYU                                      1756
#define SPECIES_IOTA                                     1757
#define SPECIES_MISSINGNO1                               1758
#define SPECIES_MISSINGNO2                               1759
#define SPECIES_MISSINGNO3                               1760
#define SPECIES_MISSINGNO4                               1761
#define SPECIES_MISSINGNO5                               1762
//end of program