//gen file for PkmnEvolved
#ifdef __INTELLISENSE__
const struct SpeciesInfo gSpeciesInfoPkmnEvolved[] =
{
#endif
#if P_FAMILY_BULBASAUR
	[SPECIES_BULBASAUR] =
	{
		.speciesName = _("Bulbasaur"),
		.baseHP = 45,
		.baseAttack = 49,
		.baseDefense = 49,
		.baseSpeed = 45,
		.baseSpAttack = 65,
		.baseSpDefense = 65,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 60,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 1,
		.evYield_SpDefense = 0,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

	[SPECIES_IVYSAUR] =
	{
		.speciesName = _("Ivysaur"),
		.baseHP = 60,
		.baseAttack = 62,
		.baseDefense = 63,
		.baseSpeed = 60,
		.baseSpAttack = 80,
		.baseSpDefense = 80,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 121,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 1,
		.evYield_SpDefense = 1,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

	[SPECIES_VENUSAUR] =
	{
		.speciesName = _("Venusaur"),
		.baseHP = 80,
		.baseAttack = 82,
		.baseDefense = 83,
		.baseSpeed = 80,
		.baseSpAttack = 100,
		.baseSpDefense = 100,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 185,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

	[SPECIES_ECOSAUR] =
	{
		.speciesName = _("Ecosaur"),
		.baseHP = 84,
		.baseAttack = 90,
		.baseDefense = 85,
		.baseSpeed = 80,
		.baseSpAttack = 118,
		.baseSpDefense = 118,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 204,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

	[SPECIES_TERARISAUR] =
	{
		.speciesName = _("Terarisaur"),
		.baseHP = 90,
		.baseAttack = 106,
		.baseDefense = 91,
		.baseSpeed = 80,
		.baseSpAttack = 129,
		.baseSpDefense = 129,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 215,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

	[SPECIES_SYMBISAUR] =
	{
		.speciesName = _("Symbisaur"),
		.baseHP = 98,
		.baseAttack = 119,
		.baseDefense = 93,
		.baseSpeed = 74,
		.baseSpAttack = 138,
		.baseSpDefense = 138,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 230,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		},

#if P_FAMILY_CHARMANDER
	[SPECIES_CHARMANDER] =
	{
		.speciesName = _("Charmander"),
		.baseHP = 39,
		.baseAttack = 52,
		.baseDefense = 43,
		.baseSpeed = 65,
		.baseSpAttack = 60,
		.baseSpDefense = 50,
		.types = MON_TYPES(TYPE_FIRE),
		.catchRate =  45,
		.expYield = 58,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 1,
		.evYield_SpAttack = 0,
		.evYield_SpDefense = 0,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		},

	[SPECIES_CHARMELEON] =
	{
		.speciesName = _("Charmeleon"),
		.baseHP = 58,
		.baseAttack = 64,
		.baseDefense = 58,
		.baseSpeed = 80,
		.baseSpAttack = 80,
		.baseSpDefense = 65,
		.types = MON_TYPES(TYPE_FIRE),
		.catchRate =  45,
		.expYield = 115,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 1,
		.evYield_SpAttack = 1,
		.evYield_SpDefense = 0,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		},

	[SPECIES_CHARIZARD] =
	{
		.speciesName = _("Charizard"),
		.baseHP = 78,
		.baseAttack = 84,
		.baseDefense = 78,
		.baseSpeed = 100,
		.baseSpAttack = 109,
		.baseSpDefense = 85,
		.types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
		.catchRate =  45,
		.expYield = 179,
		.evYield_HP = 0,
		.evYield_Attack = 0,
		.evYield_Defense = 0,
		.evYield_Speed = 0,
		.evYield_SpAttack = 3,
		.evYield_SpDefense = 0,
		.itemCommon =  ????????,
		.itemRare =  ????????,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		},

//end of program