//gen file for PkmnEvolved
#ifdef __INTELLISENSE__
const struct SpeciesInfo gSpeciesInfoPkmnEvolved[] =
{

#endif

#if P_FAMILY_BULBASAUR
	[SPECIES_BULBASAUR] =
	{
		.speciesName = _("Bulbasaur"),
		.baseHP = 45,
		.baseAttack = 49,
		.baseDefense = 49,
		.baseSpeed = 45,
		.baseSpAttack = 65,
		.baseSpDefense = 65,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 60,
		.evYield_SpAttack = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_BULBASAUR,
		.categoryName = _("Seed"),
		.height = 7,
		.weight = 69,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 356,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = -2,
		.frontPic = gMonFrontPic_Bulbasaur,
		.frontPicSize = MON_COORDS_SIZE(5,5),
		.frontPicYOffset = 16,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Bulbasaur,
		.backPicSize = MON_COORDS_SIZE(4,6),
		.backPicYOffset = 16,
		.backAnimId = BACK_ANIM_CONCAVE_ARC_SMALL,
		.palette = gMonPalette_Bulbasaur,
		.shinyPalette = gMonShinyPalette_Bulbasaur,
		.iconSprite = gMonIcon_Bulbasaur,
		.iconPalIndex = 2,
		FOOTPRINT(Bulbasaur)
		.levelUpLearnset = sBulbasaurLevelUpLearnset,
		.teachableLearnSet = sBulbasaurTeachableLearnset,
		.eggMoveLearnset = sBulbasaurTeachableLearnset,
		},

	[SPECIES_IVYSAUR] =
	{
		.speciesName = _("Ivysaur"),
		.baseHP = 60,
		.baseAttack = 62,
		.baseDefense = 63,
		.baseSpeed = 60,
		.baseSpAttack = 80,
		.baseSpDefense = 80,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 121,
		.evYield_SpAttack = 1,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_IVYSAUR,
		.categoryName = _("Seed"),
		.height = 10,
		.weight = 130,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 332,
		.pokemonOffset = 11,
		.trainerScale = 256,
		.trainerOffset = -2,
		.frontPic = gMonFrontPic_Ivysaur,
		.frontPicSize = MON_COORDS_SIZE(6,6),
		.frontPicYOffset = 10,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Ivysaur,
		.backPicSize = MON_COORDS_SIZE(6,7),
		.backPicYOffset = 10,
		.palette = gMonPalette_Ivysaur,
		.shinyPalette = gMonShinyPalette_Ivysaur,
		.iconSprite = gMonIcon_Ivysaur,
		.iconPalIndex = 2,
		FOOTPRINT(Ivysaur)
		.levelUpLearnset = sIvysaurLevelUpLearnset,
		.teachableLearnSet = sIvysaurTeachableLearnset,
		.eggMoveLearnset = sIvysaurTeachableLearnset,
		},

	[SPECIES_VENUSAUR] =
	{
		.speciesName = _("Venusaur"),
		.baseHP = 80,
		.baseAttack = 82,
		.baseDefense = 83,
		.baseSpeed = 80,
		.baseSpAttack = 100,
		.baseSpDefense = 100,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 185,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_OVERGROW, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Seed"),
		.height = 20,
		.weight = 1000,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontPic = gMonFrontPic_Venusaur,
		.frontPicSize = MON_COORDS_SIZE(7,8),
		.frontPicYOffset = 4,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Venusaur,
		.backPicSize = MON_COORDS_SIZE(6,8),
		.backPicYOffset = 10,
		.palette = gMonPalette_Venusaur,
		.shinyPalette = gMonShinyPalette_Venusaur,
		.iconSprite = gMonIcon_Venusaur,
		.iconPalIndex = 2,
		FOOTPRINT(Venusaur)
		.levelUpLearnset = sVenusaurLevelUpLearnset,
		.teachableLearnSet = sVenusaurTeachableLearnset,
		.eggMoveLearnset = sVenusaurTeachableLearnset,
		},

	[SPECIES_ECOSAUR] =
	{
		.speciesName = _("Ecosaur"),
		.baseHP = 84,
		.baseAttack = 90,
		.baseDefense = 85,
		.baseSpeed = 80,
		.baseSpAttack = 118,
		.baseSpDefense = 118,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 204,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Overgrown"),
		.height = 20,
		.weight = 2700,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontPic = gMonFrontPic_Ecosaur,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Ecosaur,
		.backPicSize = MON_COORDS_SIZE(6,8),
		.palette = gMonPalette_Ecosaur,
		.shinyPalette = gMonShinyPalette_Ecosaur,
		.iconSprite = gMonIcon_Ecosaur,
		.iconPalIndex = 2,
		FOOTPRINT(Ecosaur)
		.levelUpLearnset = sEcosaurLevelUpLearnset,
		.teachableLearnSet = sEcosaurTeachableLearnset,
		.eggMoveLearnset = sEcosaurTeachableLearnset,
		},

	[SPECIES_TERARISAUR] =
	{
		.speciesName = _("Terarisaur"),
		.baseHP = 90,
		.baseAttack = 106,
		.baseDefense = 91,
		.baseSpeed = 80,
		.baseSpAttack = 129,
		.baseSpDefense = 129,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 215,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Jungle"),
		.height = 20,
		.weight = 3500,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontPic = gMonFrontPic_Terarisaur,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Terarisaur,
		.backPicSize = MON_COORDS_SIZE(7,8),
		.palette = gMonPalette_Terarisaur,
		.shinyPalette = gMonShinyPalette_Terarisaur,
		.iconSprite = gMonIcon_Terarisaur,
		.iconPalIndex = 2,
		FOOTPRINT(Terarisaur)
		.levelUpLearnset = sTerarisaurLevelUpLearnset,
		.teachableLearnSet = sTerarisaurTeachableLearnset,
		.eggMoveLearnset = sTerarisaurTeachableLearnset,
		},

	[SPECIES_SYMBISAUR] =
	{
		.speciesName = _("Symbisaur"),
		.baseHP = 98,
		.baseAttack = 119,
		.baseDefense = 93,
		.baseSpeed = 74,
		.baseSpAttack = 138,
		.baseSpDefense = 138,
		.types = MON_TYPES(TYPE_GRASS, TYPE_POISON),
		.catchRate =  45,
		.expYield = 230,
		.evYield_SpAttack = 2,
		.evYield_SpDefense = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_CHLOROPHYLL, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_GREEN,
		.noFlip = =TRUE(),
		.cryId = CRY_VENUSAUR,
		.categoryName = _("Ecosystem"),
		.height = 20,
		.weight = 6000,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 256,
		.pokemonOffset = 1,
		.trainerScale = 375,
		.trainerOffset = 6,
		.frontPic = gMonFrontPic_Symbisaur,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Symbisaur,
		.backPicSize = MON_COORDS_SIZE(7,8),
		.palette = gMonPalette_Symbisaur,
		.shinyPalette = gMonShinyPalette_Symbisaur,
		.iconSprite = gMonIcon_Symbisaur,
		.iconPalIndex = 2,
		FOOTPRINT(Symbisaur)
		.levelUpLearnset = sSymbisaurLevelUpLearnset,
		.teachableLearnSet = sSymbisaurTeachableLearnset,
		.eggMoveLearnset = sSymbisaurTeachableLearnset,
		},

#endif

#if P_FAMILY_CHARMANDER
	[SPECIES_CHARMANDER] =
	{
		.speciesName = _("Charmander"),
		.baseHP = 39,
		.baseAttack = 52,
		.baseDefense = 43,
		.baseSpeed = 65,
		.baseSpAttack = 60,
		.baseSpDefense = 50,
		.types = MON_TYPES(TYPE_FIRE),
		.catchRate =  45,
		.expYield = 58,
		.evYield_Speed = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARMANDER,
		.categoryName = _("Lizard"),
		.height = 6,
		.weight = 85,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 410,
		.pokemonOffset = 16,
		.trainerScale = 256,
		.trainerOffset = -2,
		.frontPic = gMonFrontPic_Charmander,
		.frontPicSize = MON_COORDS_SIZE(5,5),
		.frontPicYOffset = 13,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Charmander,
		.backPicSize = MON_COORDS_SIZE(6,6),
		.backPicYOffset = 10,
		.palette = gMonPalette_Charmander,
		.shinyPalette = gMonShinyPalette_Charmander,
		.iconSprite = gMonIcon_Charmander,
		.iconPalIndex = 2,
		FOOTPRINT(Charmander)
		.levelUpLearnset = sCharmanderLevelUpLearnset,
		.teachableLearnSet = sCharmanderTeachableLearnset,
		.eggMoveLearnset = sCharmanderTeachableLearnset,
		},

	[SPECIES_CHARMELEON] =
	{
		.speciesName = _("Charmeleon"),
		.baseHP = 58,
		.baseAttack = 64,
		.baseDefense = 58,
		.baseSpeed = 80,
		.baseSpAttack = 80,
		.baseSpDefense = 65,
		.types = MON_TYPES(TYPE_FIRE),
		.catchRate =  45,
		.expYield = 115,
		.evYield_Speed = 1,
		.evYield_SpAttack = 1,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARMELEON,
		.categoryName = _("Flame"),
		.height = 11,
		.weight = 190,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 294,
		.pokemonOffset = 8,
		.trainerScale = 256,
		.trainerOffset = -2,
		.frontPic = gMonFrontPic_Charmeleon,
		.frontPicSize = MON_COORDS_SIZE(6,7),
		.frontPicYOffset = 9,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Charmeleon,
		.backPicSize = MON_COORDS_SIZE(7,7),
		.backPicYOffset = 7,
		.palette = gMonPalette_Charmeleon,
		.shinyPalette = gMonShinyPalette_Charmeleon,
		.iconSprite = gMonIcon_Charmeleon,
		.iconPalIndex = 2,
		FOOTPRINT(Charmeleon)
		.levelUpLearnset = sCharmeleonLevelUpLearnset,
		.teachableLearnSet = sCharmeleonTeachableLearnset,
		.eggMoveLearnset = sCharmeleonTeachableLearnset,
		},

	[SPECIES_CHARIZARD] =
	{
		.speciesName = _("Charizard"),
		.baseHP = 78,
		.baseAttack = 84,
		.baseDefense = 78,
		.baseSpeed = 100,
		.baseSpAttack = 109,
		.baseSpDefense = 85,
		.types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
		.catchRate =  45,
		.expYield = 179,
		.evYield_SpAttack = 3,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARIZARD,
		.categoryName = _("Flame"),
		.height = 17,
		.weight = 905,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 271,
		.trainerScale = 317,
		.trainerOffset = 3,
		.frontPic = gMonFrontPic_Charizard,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontPicYOffset = 1,
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Charizard,
		.backPicSize = MON_COORDS_SIZE(7,8),
		.backPicYOffset = 4,
		.palette = gMonPalette_Charizard,
		.shinyPalette = gMonShinyPalette_Charizard,
		.iconSprite = gMonIcon_Charizard,
		.iconPalIndex = 2,
		FOOTPRINT(Charizard)
		.levelUpLearnset = sCharizardLevelUpLearnset,
		.teachableLearnSet = sCharizardTeachableLearnset,
		.eggMoveLearnset = sCharizardTeachableLearnset,
		},

	[SPECIES_CHARIGUANA] =
	{
		.speciesName = _("Chariguana"),
		.baseHP = 83,
		.baseAttack = 96,
		.baseDefense = 78,
		.baseSpeed = 117,
		.baseSpAttack = 118,
		.baseSpDefense = 85,
		.types = MON_TYPES(TYPE_FIRE, TYPE_FLYING),
		.catchRate =  45,
		.expYield = 199,
		.evYield_SpAttack = 3,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_BLAZE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_RED,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARIZARD,
		.categoryName = _("Inferno"),
		.height = 24,
		.weight = 1104,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 271,
		.trainerScale = 317,
		.trainerOffset = 3,
		.frontPic = gMonFrontPic_Chariguana,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Chariguana,
		.backPicSize = MON_COORDS_SIZE(8,8),
		.backPicYOffset = 5,
		.palette = gMonPalette_Chariguana,
		.shinyPalette = gMonShinyPalette_Chariguana,
		.iconSprite = gMonIcon_Chariguana,
		.iconPalIndex = 2,
		FOOTPRINT(Chariguana)
		.levelUpLearnset = sChariguanaLevelUpLearnset,
		.teachableLearnSet = sChariguanaTeachableLearnset,
		.eggMoveLearnset = sChariguanaTeachableLearnset,
		},

	[SPECIES_CHARIANA] =
	{
		.speciesName = _("Chariana"),
		.baseHP = 91,
		.baseAttack = 108,
		.baseDefense = 78,
		.baseSpeed = 127,
		.baseSpAttack = 132,
		.baseSpDefense = 85,
		.types = MON_TYPES(TYPE_FIRE, TYPE_WATER),
		.catchRate =  45,
		.expYield = 211,
		.evYield_SpAttack = 3,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_MARVEL_SCALE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_BLUE,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARIZARD,
		.categoryName = _("Depth"),
		.height = 30,
		.weight = 1542,
		.description = COMPOUD_STRING(
			“temp”),
		.pokemonScale = 271,
		.trainerScale = 317,
		.trainerOffset = 3,
		.frontPic = gMonFrontPic_Chariana,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Chariana,
		.backPicSize = MON_COORDS_SIZE(8,8),
		.backPicYOffset = 6,
		.palette = gMonPalette_Chariana,
		.shinyPalette = gMonShinyPalette_Chariana,
		.iconSprite = gMonIcon_Chariana,
		.iconPalIndex = 2,
		FOOTPRINT(Chariana)
		.levelUpLearnset = sCharianaLevelUpLearnset,
		.teachableLearnSet = sCharianaTeachableLearnset,
		.eggMoveLearnset = sCharianaTeachableLearnset,
		},

	[SPECIES_CHARIATHAN] =
	{
		.speciesName = _("Chariathan"),
		.baseHP = 93,
		.baseAttack = 132,
		.baseDefense = 80,
		.baseSpeed = 127,
		.baseSpAttack = 139,
		.baseSpDefense = 88,
		.types = MON_TYPES(TYPE_FIRE, TYPE_WATER),
		.catchRate =  45,
		.expYield = 220,
		.evYield_SpAttack = 3,
		.genderRatio = PERCENT_FEMALE(12.5),
		.eggCycles =  20,
		.friendship = STANDARD_FRIENDSHIP,
		.growthRate = MEDIUM_FAST,
		.eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
		.abilities = { ABILITY_MARVEL_SCALE, ABILITY_NONE , ABILITY_NONE },
		.bodyColor = BODY_COLOR_PURPLE,
		.noFlip = =TRUE(),
		.cryId = CRY_CHARIZARD,
		.categoryName = _("Abyss"),
		.height = 102,
		.weight = 3694,
		.description = COMPOUD_STRING(
			"test"),
		.pokemonScale = 271,
		.trainerScale = 317,
		.trainerOffset = 3,
		.frontPic = gMonFrontPic_Chariathan,
		.frontPicSize = MON_COORDS_SIZE(8,8),
		.frontAnimFrames = ANIM_FRAMES(ANIMCMD_FRAME(0, 1)),
		.frontAnimId = ANIM_V_JUMPS_H_JUMPS,
		.frontAnimDelay = 15,
		.backPic = gMonBackPic_Chariathan,
		.backPicSize = MON_COORDS_SIZE(6,8),
		.backPicYOffset = 8,
		.palette = gMonPalette_Chariathan,
		.shinyPalette = gMonShinyPalette_Chariathan,
		.iconSprite = gMonIcon_Chariathan,
		.iconPalIndex = 2,
		FOOTPRINT(Chariathan)
		.levelUpLearnset = sChariathanLevelUpLearnset,
		.teachableLearnSet = sChariathanTeachableLearnset,
		.eggMoveLearnset = sChariathanTeachableLearnset,
		},

#endif
